name: Build & Push (API/Web/Worker)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api", "web", "worker" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set image meta
        id: meta
        run: |
          IMAGE=${{ env.DOCKERHUB_USERNAME }}/app-${{ matrix.service }}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF##*/}" == v* ]]; then
            TAG="${GITHUB_REF##*/}"   # exemple v1.0.0
          else
            TAG="1.0.0"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ stalk3 }}
          password: ${{ dckr_pat_eWvZGnM1C93qaCGXUD6eKxMVLVQ }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ steps.meta.outputs.image }}:latest
